### ISSUE TITLE
Avoid observation-by-observation construction of UnivariateFinite objects in MLJ interface

### ISSUE THREAD

**Issue by ablaom** [sylvaticus/BetaML.jl#19] opened 2021-03-04 22:14 UTC
The overhead for constructing `UnivariateFinite` objects *one at a time* is [very high](https://github.com/alan-turing-institute/MLJ.jl/issues/511). For this reason a `UnivariateFiniteArray` implementation of `AbstractArray{<:UnivariateFinite}` was developed. This includes optimised implementations of broadcasting `pdf`, and so forth.  

I recommend that in the BetaML classifiers one contruct probabilistic predictions by applying the `UnivariateFinite(...)` constructor (which can construct arrays as well as singletons) to the full matrix of probabilities (with all observations in it). You can see examples of this in all the MLJ probabilistic classifier interfaces. I am copying the doc-string for this constructor below:

cc @OkonSamuel 

---

    UnivariateFinite(support,
                     probs;
                     pool=nothing,
                     augmented=false,
                     ordered=false)

Construct a discrete univariate distribution whose finite support is
the elements of the vector `support`, and whose corresponding
probabilities are elements of the vector `probs`. Alternatively,
construct an abstract *array* of `UnivariateFinite` distributions by
choosing `probs` to be an array of one higher dimension than the array
generated.

Unless `pool` is specified, `support` should have type
 `AbstractVector{<:CategoricalValue}` and all elements are assumed to
 share the same categorical pool, which may be larger than `support`.

*Important.* All levels of the common pool have associated
probabilities, not just those in the specified `support`. However,
these probabilities are always zero (see example below).

If `probs` is a matrix, it should have a column for each class in
`support` (or one less, if `augment=true`). More generally, `probs`
will be an array whose size is of the form `(n1, n2, ..., nk, c)`,
where `c = length(support)` (or one less, if `augment=true`) and the
constructor then returns an array of size `(n1, n2, ..., nk)`.

```
using CategoricalArrays
v = categorical([:x, :x, :y, :x, :z])

julia> UnivariateFinite(classes(v), [0.2, 0.3, 0.5])
UnivariateFinite{Multiclass{3}}(x=>0.2, y=>0.3, z=>0.5)

julia> d = UnivariateFinite([v[1], v[end]], [0.1, 0.9])
UnivariateFinite{Multiclass{3}(x=>0.1, z=>0.9)

julia> rand(d, 3)
3-element Array{Any,1}:
 CategoricalArrays.CategoricalValue{Symbol,UInt32} :z
 CategoricalArrays.CategoricalValue{Symbol,UInt32} :z
 CategoricalArrays.CategoricalValue{Symbol,UInt32} :z

julia> levels(d)
3-element Array{Symbol,1}:
 :x
 :y
 :z

julia> pdf(d, :y)
0.0
```

### Specifying a pool

Alternatively, `support` may be a list of raw (non-categorical)
elements if `pool` is:

- some `CategoricalArray`, `CategoricalValue` or `CategoricalPool`,
  such that `support` is a subset of `levels(pool)`

- `missing`, in which case a new categorical pool is created which has
  `support` as its only levels.

In the last case, specify `ordered=true` if the pool is to be
considered ordered.

```
julia> UnivariateFinite([:x, :z], [0.1, 0.9], pool=missing, ordered=true)
UnivariateFinite{OrderedFactor{2}}(x=>0.1, z=>0.9)

julia> d = UnivariateFinite([:x, :z], [0.1, 0.9], pool=v) # v defined above
UnivariateFinite(x=>0.1, z=>0.9) (Multiclass{3} samples)

julia> pdf(d, :y) # allowed as `:y in levels(v)`
0.0

v = categorical([:x, :x, :y, :x, :z, :w])
probs = rand(100, 3)
probs = probs ./ sum(probs, dims=2)
julia> UnivariateFinite([:x, :y, :z], probs, pool=v)
100-element UnivariateFiniteVector{Multiclass{4},Symbol,UInt32,Float64}:
 UnivariateFinite{Multiclass{4}}(x=>0.194, y=>0.3, z=>0.505)
 UnivariateFinite{Multiclass{4}}(x=>0.727, y=>0.234, z=>0.0391)
 UnivariateFinite{Multiclass{4}}(x=>0.674, y=>0.00535, z=>0.321)
   ⋮
 UnivariateFinite{Multiclass{4}}(x=>0.292, y=>0.339, z=>0.369)
```

### Probability augmentation

Unless `augment=true`, sums of elements along the last axis (row-sums
in the case of a matrix) must be equal to one, and otherwise such an
array is created by inserting appropriate elements *ahead* of those
provided. This means the provided probabilities are associated with
the the classes `c2, c3, ..., cn`.

---

    UnivariateFinite(prob_given_class; pool=nothing, ordered=false)

Construct a discrete univariate distribution whose finite support is
the set of keys of the provided dictionary, `prob_given_class`, and
whose values specify the corresponding probabilities.

The type requirements on the keys of the dictionary are the same as
the elements of `support` given above with this exception: if
non-categorical elements (raw labels) are used as keys, then
`pool=...` must be specified and cannot be `missing`.

If the values (probabilities) are arrays instead of scalars, then an
abstract array of `UnivariateFinite` elements is created, with the
same size as the array.

**Comment by ablaom** [comment] 2021-03-04 22:21
Notice that you can alternatively pass a *dictionary* `prob_given_class` of arrays to the constructor, if that is more convenient (see near the end of the docstring).

**Comment by sylvaticus** [comment] 2021-03-06 18:24
Hello, thank you for your suggestions. I can't get the last constructor working:

`predictions = MMI.UnivariateFinite(modelPredictions,pool=fittedModel.classes)` # MethodError

Where `modelPredictions` is a vector of `Dict{String,Float64}` (the non-zero probabilities for each class) and `fittedModel.classes` is the vector of the raw classes as strings.

**Comment by ablaom** [comment] 2021-03-07 00:32
I believe it expects a dictionary keyed on classes whose values are arrays, not a vector of dictionaries.

**Comment by ablaom** [comment] 2021-03-07 00:33
If you are contructing vectors of dictionaries, that might also be a performance issue, no?

**Comment by OkonSamuel** [comment] 2021-03-07 10:52
Could you post the full error message you are getting so i can debug

**Comment by sylvaticus** [comment] 2021-03-07 13:45
@OkonSamuel this is a minimal example. I believe the problem is those highlighted by @ablaom , that the method is expecting an other kind of dictionary, not a vector of dictionaries of PMF. Not much a problem, I will construct a matrix of the output and use one of the other constructors. Compared with the rest of the algorithm, the hoverheads of building a Dictionary is pretty negligeable.

```
import MLJBase; const Mlj = MLJBase

classes = ["green","red","blue"]

fitResults = [
  Dict("green" => 4.0,"blue" => 6.0),
  Dict("red" => 2.5, "blue"=> 7.5),
  Dict("green" => 2.5, "blue"=>1.5,"red"=>5.0)
]

yhat = predictions = Mlj.UnivariateFinite(fitResults,pool=classes)
```
```
ERROR: Exception handling log message: MethodError(findfirst, (Base.var"#411#413"(), Any[:returnTuple]), 0x0000000000006e71)
  module=Base  file=errorshow.jl  line=334
  Second exception: MethodError(findfirst, (Base.var"#411#413"(), Any[:returnTuple]), 0x0000000000006e71)
MethodError: no method matching UnivariateFinite(::MLJModelInterface.FullInterface, ::Array{Dict{String,Float64},1}; pool=["green", "red", "blue"])
Stacktrace:
 [1] UnivariateFinite(::Array{Dict{String,Float64},1}; kwargs::Base.Iterators.Pairs{Symbol,Array{String,1},Tuple{Symbol},NamedTuple{(:pool,),Tuple{Array{String,1}}}}) at /home/lobianco/.julia/packages/MLJModelInterface/McKyQ/src/data_utils.jl:433
 [2] MLJBase.UnivariateFinite(::Array{Dict{String,Float64},1}; kwargs::Base.Iterators.Pairs{Symbol,Array{String,1},Tuple{Symbol},NamedTuple{(:pool,),Tuple{Array{String,1}}}}) at /home/lobianco/.julia/packages/MLJBase/D3M4n/src/univariate_finite/types.jl:33
 [3] top-level scope at none:1
```

**Comment by sylvaticus** [comment] 2021-03-07 13:58
Implemented `predictions = MMI.UnivariateFinite(classes, predMatrix)` instead of 

`predictions = [MMI.UnivariateFinite(classes, predMatrix[i,:]) for i in 1:nRecords] `

in all the MLJ interfaces to probabilistic models (commit [1c5a7ac](https://github.com/sylvaticus/BetaML.jl/commit/1c5a7ac2d8b1f02ccb93744e3940db762b75837b) ).

**Comment by sylvaticus** [comment] 2021-03-19 21:48
Closing, as implemented...

**Closed by sylvaticus** 2021-03-19 21:48 UTC
